services:

  api:
    build: .
    command: snacksbar:app
    ports:
    - 8000:8000
    environment:
    - OAUTH_TOKEN_URL=http://localhost:8001/token
    - CACHE_DB_URL=redis://cache:6379/0
    - SNACKSBAR_DB_URL=postgresql://snacksbar:snacksbar@db:5432/snacksbar
    depends_on:
    - db
    - cache

  auth:
    build: .
    command: authserver:app
    ports:
    - 8001:8000
    environment:
    - AUTHSERVER_DB_URL=postgresql://authserver:authserver@db:5432/authserver
    depends_on:
    - db

  migration:
    build: .
    entrypoint: alembic upgrade head
    environment:
    - AUTHSERVER_DB_URL=postgresql://authserver:authserver@db:5432/authserver
    - SNACKSBAR_DB_URL=postgresql://snacksbar:snacksbar@db:5432/snacksbar
    depends_on:
    - api
    - auth
    - db
    restart: on-failure

  db:
    image: postgres:14.2
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=postgres
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

  cache:
    image: redis:6.2.6
    ports:
    - 6379:6379
