"""Initial migrations

Revision ID: 62693f203676
Revises: 
Create Date: 2022-02-28 19:55:35.443505

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "62693f203676"
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_authserver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_authserver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_snacksbar():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.DECIMAL(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "drink",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.DECIMAL(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingredient",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.DECIMAL(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "snack",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "snacks_have_ingredients",
        sa.Column("snack_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snack_id"],
            ["snack.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade_snacksbar():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snacks_have_ingredients")
    op.drop_table("snack")
    op.drop_table("ingredient")
    op.drop_table("drink")
    op.drop_table("category")
    # ### end Alembic commands ###
